import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import {useOpenAi} from 'nextai'
// import useOpenAi from ''
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const ai = useOpenAi("text-davinci-002");
  const [text, settext] = React.useState<string>("")
  const [res, setRes] = React.useState('')
  const submitHandler = async (e: any) => {
    e.preventDefault()
    const data = await ai.submit(text)
    console.log(data)
    setRes(data)
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>{ai.loading}</p>
        <p>{`${res}`}</p>
        <p>{ai.errorMessage}</p>
        <form onSubmit={submitHandler}>
          <input onChange={(e) => settext(e.target.value)} />
          <button >Submit</button>
        </form>
       
      </main>
    </>
  )
}
